import { Component, ViewEncapsulation } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import {
  ArrowRight,
  Bot,
  Brain,
  Building2,
  CalendarDays,
  ChartNoAxesColumn,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Code2,
  Cpu,
  Database,
  Facebook,
  Factory,
  Globe2,
  GraduationCap,
  HeartPulse,
  Instagram,
  LUCIDE_ICONS,
  LineChart,
  Linkedin,
  Landmark,
  LucideIconProvider,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  Palette,
  Phone,
  Plane,
  Rocket,
  Settings,
  Search,
  Share2,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Store,
  Target,
  Users,
  Video,
  Workflow,
  X
} from 'lucide-angular';
import { NavbarComponent } from './layout/navbar/navbar.component';
import { FooterComponent } from './layout/footer/footer.component';

const icons = {
  ArrowRight,
  Bot,
  Brain,
  Building2,
  CalendarDays,
  ChartNoAxesColumn,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Code2,
  Cpu,
  Database,
  Facebook,
  Factory,
  Globe2,
  GraduationCap,
  HeartPulse,
  Instagram,
  LineChart,
  Linkedin,
  Landmark,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  Palette,
  Phone,
  Plane,
  Rocket,
  Settings,
  Search,
  Share2,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Store,
  Target,
  Users,
  Video,
  Workflow,
  X
};

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [NavbarComponent, RouterOutlet, FooterComponent],
  providers: [{ provide: LUCIDE_ICONS, multi: true, useValue: new LucideIconProvider(icons) }],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
  encapsulation: ViewEncapsulation.None
})
export class AppComponent {}
